// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: chat.sql

package query

import (
	"context"
)

const createOrUpdateChat = `-- name: CreateOrUpdateChat :exec
INSERT INTO chats (user_id) VALUES ($1)
ON CONFLICT(user_id)
DO UPDATE SET active_at = NOW()
`

func (q *Queries) CreateOrUpdateChat(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, createOrUpdateChat, userID)
	return err
}
