// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	UserID    int64
	CreatedAt pgtype.Timestamptz
	ActiveAt  pgtype.Timestamptz
}

type Document struct {
	ID        int64
	FileID    string
	ChatID    int64
	Hash      pgtype.UUID
	Ocr       []byte
	CreatedAt pgtype.Timestamptz
}
