-- +goose Up
-- +goose StatementBegin
CREATE TABLE documents (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    file_id VARCHAR(100) NOT NULL,
    chat_id BIGINT NOT NULL,
    hash UUID NOT NULL,
    ocr JSON,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(hash, chat_id)
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE documents
-- +goose StatementEnd
